### ISSUE TITLE
会計報告所

### ISSUE THREAD

**Issue by PharaohKJ** [osunc-kanazawa/osunc-kanazawa#1]
会計報告はここで行って下さい。

会議後、数字があって、精算が終わったらクローズ。

**Comment by takuya-matsumura** [comment]
予算管理も会計？
であれば，おおよそ，収入と支出の内訳のたたき台の素案を出してもらえるといいなぁ，と．

**Comment by nkmc-ja** [comment]
会計は私担当で。Googleスプレッドシート作成後に公開します。
予算管理もやってみます・・・。

**Comment by nkmc-souya** [comment]
会計から報告です。
会場参加者は（カウントが正確ではありませんが）
　一般：45名　学生：6名
懇親会参加者は３１名
となっております。

収支については
プラス \57,064 となっております。
未清算の仮払いはない認識ですが、もしございましたらご連絡ください。

詳細については以下の通りです。
https://docs.google.com/spreadsheets/d/1azGY_Sv4tllFmcKgJFN9j24ThGu0e8JQpdpxU6Fly20/edit

プラス分についていは、石川でコミュニティイベントを開催する会として、今後のイベント開催に繰り越しとさせていただこうと思います。
余剰金については、現在、私の方でお預かりしておりますが、問題がなければこのまま保管いたします。

**Comment by PharaohKJ** [comment]
このxlsで問題ないと思います。お金の受け渡しなど、完了したらクローズしましょう。

**Comment by nkmc-souya** [comment]
本日 @PharaohKJ さんから、XLSへ記入済みの
\23,400 　（会場費・予備費(\54.000) - 会場費(\30,600) ）  を
受け取りました。
余剰金は\57,064 となります。
これでCloseいたします。
