### ISSUE TITLE
受付の準備と運営

### ISSUE THREAD

**Issue by PharaohKJ** [osunc-kanazawa/osunc-kanazawa#10]
- [ ] 担当者決定
- [x] 集金方法決定
- [ ] 受付配布物
  - [x] ネームプレート(撮影OK/NGが一目わかるように2種用意すること)
    - 赤・青・黄・緑の4色を @tmiyahar さんにお借りする
  - [ ] ほか

**Comment by tmiyahar** [comment]
ネームプレートは4色（赤、青、黄、緑）が用意できます。

**Comment by PharaohKJ** [comment]
ありがとうございます。お借りします。

**Comment by tmiyahar** [comment]
大体、以下のような色分けかな〜。

一般：緑
学生：黄
スタッフ：青
顔出し不可：赤

黄色と緑は逆だったかも。今、外出先なので確認できないので、後で修正するかもしれません。

**Comment by nkmc-souya** [comment]
午前中、受付担当をします。
また、会計として参加費のおつりを用意しておきますね。

会場設営時に、入り口付近に受付用の机を１つ用意お願いします。

こちらで用意するものは
- 来場者のチェックリスト（２部）
- おつり(1,000円札で、2～3万円分ぐらい？）
- ボールペン２つ
- マジック？

対応する内容は
- 来場者の受付（チェックリスト照合）
- 参加費の徴収（カンファレンス分のみ）
- 一般、学生、スタッフ、撮影ＯＫ、ＮＧを確認し、 ネームプレートを渡す
- 展示者、発表者には案内をする

他
-  お土産があれば受付で対応しようと思います（いただいた方のお名前、品物のメモ、品物の預かり
-  懇親会の受付は懇親会担当者が行うとのことです

**Comment by nkmc-souya** [comment]
確認事項

１．ネームプレートは紙を入れるタイプでしょうか。その場合、名刺が入るサイズと思えばよいですかね。
受付に、カードサイズの紙とマジックを用意しようと思います。

２．会場設営担当の方、展示希望の方が来られた場合の、誘導をお願いしたく。また、受付の机を入り口近くに設営する手はずでお願いします。（設置はこちらでやれますんで、位置を相談）

**Comment by takuya-matsumura** [comment]
中道の書き込みで気になった点があります．
・「午前中，受付担当をする」とのことですが，午後は誰がするのでしょうか？
・懇親会の費用は，懇親会担当者が行うとのことですが，受付で二人，並んで行う感じでしょうか？
（一度に行う方が払う側としたら楽だなぁ，と）

創屋メンバーの分の参加費用は事前回収しませんか．当日，スタッフとして動いていると払い忘れそうなので．（懇親会の分も）

**Comment by PharaohKJ** [comment]
受付は大金が置かれるでしょうので、最低2人体制で回すことにしましょう。
特に午前〜午後イチぐらいはお土産、会場設営案内もあると思うので3人体制がいいと思います。

特に午後になると、みんなプレゼンとかもあるでしょうから結構シビアになると思いますので
ここで担当割してしまえばいいんじゃないでしょうか。

フローとしては @nkmc-souya さんの方法でいいんじゃないでしょうか。あと領収証希望者には出さねばならぬかもですね。どんな名前使うかは決めておきますか。 **オープンソースアンカンファレンス金沢** でいいですか？

> 懇親会の受付は懇親会担当者

これはどこまでをさしているのかピンとこない感じですが、受付で会費をお預かりし、17時閉場時に懇親会担当者( @YMatsubara さんかな ) にお渡しする。でいいんじゃないでしょうか。connpassにあるように

> 当日滑り込み参加希望の場合は、会場にてスタッフにお声がけください！

とありますので、この「当日滑り込み」の場合のみ、 @YMatsubara さんにお声がけする、でいいのではないでしょうか。

創屋さまでまとめるというのはおまかせします。

**Comment by PharaohKJ** [comment]
担当割(勝手に立候補して書く、修正して下さい)

## 役割

受付→チェックリストをみてネームプレートなど
会計→領収証、集金、お金の管理など
案内→お土産受け取り、設営案内など

## 受付について
- 懇親会に出席しないかたは参加費のみ徴収し、名寄せなしでOK

### 渡すネームプレート
- 一般：透明
- 学生：黄
- スタッフ：青
- 顔出し不可：赤

## 担当役割表

| 時間 | 受付 | 会計 | 案内 | ※ |
| :-- | --- | --- | --- | --- |
| 10:00 | @nkmc-souya | @takuya-matsumura | @PharaohKJ | - |
| 11:00 | @nkmc-souya | @takuya-matsumura | @PharaohKJ | - |
| 12:00 | @YMatsubara | @takuya-matsumura | @Yuk11 | - |
| 13:00 | @YMatsubara | @takuya-matsumura | @Yuk11 | ケータリング受取 & 支払 |
| 14:00 | @YMatsubara | @takuya-matsumura | @Yuk11 | - |
| 15:00 | @rYagi | @takuya-matsumura | - | - |
| 16:00 | @rYagi | @takuya-matsumura | - | - |

## 会場レイアウト

[画像](https://www.dropbox.com/s/gwv2oe2c2nt2hnp/レイアウト.png?dl=0)

**Comment by tmiyahar** [comment]
ネームプレートは何枚ずつ用意したらいいですかね〜。多めに持って行くのは構わないので、ざっくりと枚数を検討してみてください。

基本的な文房具はいつもOSCで使っているセットを持って行こうと思っています。筆記用具なども含めて一式大丈夫です。

領収書はびぎねっとで作成可能なので、これも金額、大体の枚数（作成は4枚/A4 1ページなので4の倍数）を教えてくれれば作れます。

**Comment by tmiyahar** [comment]
あと、参加者リストのチェック（名寄せ）は、やらないでいいと思いますよ。

出欠人数をシビアに確認しないといけないならば懇親会はチェックした方がいいかもしれません。
日中だけの一般参加はあまり気にせずにいいと思います。

**Comment by YMatsubara** [comment]
懇親会の参加者だけは受付時に名簿にチェックさせていただいて、お金をお預かりする形としたいです。

・懇親会に参加されない方は、名前チェックなしで参加費用をお支払いいただく。
・懇親会に参加される方は、懇親会の名簿にチェックと懇親会費用、参加費用をお支払いいいただく。

という形でよろしいでしょうか？

**Comment by takuya-matsumura** [comment]
宮原さん，領収書について質問です．
金額欄を空欄にしといて，受付時に内容に応じ1,000円，2,000円，5,000円，6,000円，7,000円の金額を手書きするのでもよいのでしょうか？
これで良いのであれば，参加者人数分の枚数を用意しとけば，なんとかなりますね．
今の感じだと40枚もあれば十分なのかな？

**Comment by nkmc-souya** [comment]
> ネームプレートは何枚ずつ用意したらいいですかね〜。多めに持って行くのは構わないので、ざっくりと枚数を検討してみてください。

一般： 透明＆白紐 × 65
学生： 黄 × 10
スタッフ：青 × 18
顔出し不可： 赤 × 11

現在、申し込みの中にスタッフの人数も入っていますので、多めに見ています。

※宮原：在庫数などの関係で、色が変更になったり、数が調整されています。

**Comment by YMatsubara** [comment]
お昼から14時までは受付に立ちます。懇親会参加の方もその時間までにはほとんど集まってくれると思うので、人数のブレが出ても対応がしやすいと思いますので。

ただ、グラフの編集の仕方がわからないのですが。お願いできないでしょうか？

**Comment by PharaohKJ** [comment]
@YMatsubara さん、対象の書き込みの右上、鉛筆マークをクリックで編集です。
書式については入力テキストエリアのしたの方に「Styling with Markdown is Supported」とあるのでそれを参照してください。

**Comment by YMatsubara** [comment]
ありがとうございます。
自分の投稿以外は、鉛筆マークが表示されなくて困っておりました。何か設定なのでしょうか？
グラフに反映していただいているようで、申し訳ないです。

**Comment by PharaohKJ** [comment]
おっと、失礼しました。権限の問題でした。修正しておきました。

**Comment by YMatsubara** [comment]
ありがとうございます。確認しました。

**Comment by tmiyahar** [comment]
受付方法はいいと思います！

領収書は、以下のようにしましょう（4の倍数）。

昼の部用
2000円×8枚
1000円×48枚
無記入×8枚

懇親会用
5000円×40枚

飛び入りが増えて足りなくなったら、何とかします。

**Comment by takuya-matsumura** [comment]
領収書をお渡しするのは，必要な方だけでよいのですよね．
枚数，足りそうな予感がします．

**Comment by takuya-matsumura** [comment]
時間ごとの担当割り　空欄が埋まらないので，創屋メンバーで埋めます．
案内は，途中で必要無くなるはずなので，空欄のままにしておきます．

**Comment by tmiyahar** [comment]
名札の準備、完了しました。一部色が変わったり、数量が変わってます。

懇親会用の識別を考えましたが、大変そうなのでやめました。

**Comment by PharaohKJ** [comment]
https://github.com/osunc-kanazawa/osunc-kanazawa/issues/10#issuecomment-241339200

の渡すネームプレートを緑 → 透明に変更しました。

**Comment by tmiyahar** [comment]
宮原が持って行くものは以下で合ってますか？

・名札関係一式 準備完了
・領収書関係一式  準備中
・必要そうな文房具少々 準備ﾏﾀﾞｰ
・必要そうな張り紙少々 準備ﾏﾀﾞｰ

**Comment by PharaohKJ** [comment]
無事完了しました。
