### ISSUE TITLE
スポンサー募集の仕組みについて

### ISSUE THREAD

**Issue by PharaohKJ** [osunc-kanazawa/osunc-kanazawa#11]
広報活動をするのですが、なかなかどうすれば貢献いただけるのか？ということを具体的に提示しないとなかなか難しいということで、以下のプランを提示していこうと考えるのですがどうでしょうか？
## ブロンズスポンサー
- ご提供いただくもの
  - ステッカー、ペラ、など印刷物を展示会場に展示
- 特典
  - 資料・ウェブページへのロゴ掲載
  - 宣伝などLT1枠
## シルバースポンサー
- ご提供いただくもの
  - ステッカー、ペラ、など印刷物を展示会場に展示(あれば)
  - 来場者の食べる飲食物の提供
    - 当日、直接お持ちいただくか、我々が買い出しにいきます
    - 金額の場合、￥2,000- ほど
- 特典
  - 資料・ウェブページへのロゴ掲載
  - 展示会場にスペース1
  - 宣伝などLT1枠
  - スポンサー入場1人
## ゴールドスポンサー
- ご提供いただくもの
  - ステッカー、ペラ、など印刷物を展示会場に展示(あれば)
  - 来場者の食べる飲食物の提供
    - 当日、直接お持ちいただくか、我々が買い出しにいきます
    - 金額の場合、￥5,000- ほど
- 特典
  - 資料・ウェブページへのロゴ掲載
  - 展示会場にスペース2
  - 宣伝などLT3枠
  - スポンサー入場3人

**Comment by takuya-matsumura** [comment]
初開催でここまでやります？
どれだけ集客できるかも定かでないので，次回以降の取り組みにすればいいのでは．
展示（パンフ置いたり，デモ置いたり）用長机1つ 幾らみたいなのでどうですか？
展示が多いから，長机二つ分のスペースが欲しいとなると倍の金額になる．

**Comment by PharaohKJ** [comment]
じゃあそれでいきましょう。
- 長机一つ1000円ぐらい。
- 展示いただければ社名ロゴ商品名など掲載させていただきます。
- お金は飲食含む会場費に使わせていただきます。

ということで。どうでしょ？

2016年6月1日(水) 8:49 Takuya Matsumura notifications@github.com:

**Comment by tmiyahar** [comment]
協賛費用は会場費などに割り当てる感じがいいかなと。なので、無料参加枠は無くてもいい気がします。現物出資は分かりにくくなるので、そこは一般参加者として扱えば良いような？

LT宣伝枠を用意すると、宣伝で白けて逆効果にならないかという懸念があるので、むしろ普通にLTエントリーしてもらって宣伝的な事もオッケーよ、の方がいいかも？

机は制限のある面積内で頑張れ、という方が面白いかなー。

**Comment by PharaohKJ** [comment]
それでは

スポンサー募集
- 長机1つ + 椅子2つ ￥1,000- (利用方法はご自由に)
- 展示いただければ社名ロゴ商品名など掲載させていただきます。
- お金は飲食含む会場費に使わせていただきます。
- LTエントリーぜひお願いします。

こんなところでいきましょうかね？

**Comment by PharaohKJ** [comment]
これでいきます。(というかこの内容をかりギメとして Civic Hack Night で話してきました。

https://codeforkanazawa.doorkeeper.jp/events/46358

20人ぐらいいらっしゃってまして、会場(ITプラザ武蔵)がぜひ協力して進めたいとの言質いただきました。

**Comment by PharaohKJ** [comment]
これも料金きまって、申し込みももう埋まりそうなのでクローズします。
