### ISSUE TITLE
募集ページの更新

### ISSUE THREAD

**Issue by PharaohKJ** [osunc-kanazawa/osunc-kanazawa#12]
本会
http://connpass.com/event/30813/
懇親会
http://connpass.com/event/30846/
に更新してほしいこと、などあればこちらで。

**Comment by PharaohKJ** [comment]
https://github.com/osunc-kanazawa/osunc-kanazawa/issues/5#issuecomment-222570324

にあわせて価格変更をして欲しいです。

**Comment by nkmc-ja** [comment]
> #5 (comment)
> にあわせて価格変更をして欲しいです。

既存申し込み区分３つを一般向けとして、2,000円で統一しました。
追加で
学生：1,000円
高校生以下：無料
で申し込みできるようにしました。

学生・高校生以下の展示、発表申し込みは、申込時のアンケートで受け付けるように記載してあります。

**Comment by nkmc-ja** [comment]
展示スペース希望の方は、+1,000円としています。
ただし同一団体・企業から、複数名で参加される場合は、
・一般（展示発表棒）＋一般
のように組み合わせで申し込みしてもらうことになります
（告知サイトの仕組み上、申し込み後の枠の変更ができないので）

**Comment by PharaohKJ** [comment]
無事完了しました。
