### ISSUE TITLE
会場レイアウトの決定

### ISSUE THREAD

**Issue by PharaohKJ** [osunc-kanazawa/osunc-kanazawa#2]
- [x] レイアウトの決定
- [x] 出展可能数の確定

予算やケータリングに絡むと思うのでとりあえず6月半ばまでには仮決定すること。

**Comment by PharaohKJ** [comment]
@Yuk11 6月半ばもすぎそうですが、どうですか？レイアウト決めましょう。会場図もって出展営業します。

**Comment by yukimuraaa** [comment]
すみません、遅くなりました。
ざっくりですが、エクセルで作りました。
青色机はconnpassで募集している枠の数あり、緑色机は増やせる募集枠の数（5枠）あります。
飲食物の机はテーブル繋げて1つにする想定をしていますが、飲み物と食べ物で分けてもいいかもしれません。
https://www.dropbox.com/s/5swju66qkvor9s6/%E3%83%AC%E3%82%A4%E3%82%A2%E3%82%A6%E3%83%88.xlsx?dl=0

**Comment by PharaohKJ** [comment]
ありがとうございます。だいたい15席ぐらいですかね。各位どうでしょう？
15出展いただけるようがんばります。

@tmiyahar さん、何かあればぜひレビューいただきたいです。

@Yuk11 さん、あと、大変とってもワガママいって申し訳ありませんが、エクセル持ってないので、
エクセルでどう見えているかスクリーンショットの画像もいっしょにいただけますでしょうか。

**Comment by yukimuraaa** [comment]
@PharaohKJ 失礼しました、スクリーンショットです。 https://www.dropbox.com/s/gwv2oe2c2nt2hnp/%E3%83%AC%E3%82%A4%E3%82%A2%E3%82%A6%E3%83%88.png?dl=0

**Comment by PharaohKJ** [comment]
レイアウトはこれで決定、出展可能数は15ということで close します。
