### ISSUE TITLE
懇親会場の決定

### ISSUE THREAD

**Issue by PharaohKJ** [osunc-kanazawa/osunc-kanazawa#3]
- [x] 予算決め
- [x] 場所決め
- [x] 人数決め
- [x] 移動方法の決定

**Comment by PharaohKJ** [comment]
@YMatsubara さんの担当予定。

**Comment by YMatsubara** [comment]
予算　4000円以内
場所　徒歩圏内（15分）
人数　未定
移動方法　徒歩

あと、30名規模の座敷があるかどうか
当日の人数変更に柔軟に対応できるか
を基準に探しています。

地元の食材にこだわると、値段が跳ね上がるので、
大衆居酒屋で、1次会。行きたい方で2次会

という流れではいかがでしょうか？？

とりあえず、現段階での候補のお店を記載します。
候補のお店
★金澤串揚げ　ざしき笑し
050-5281-2966
石川県金沢市中橋町11-1
営業時間17:00～翌25:00

串揚げ屋さん
30名の座敷完備
座敷貸し切りは要相談（おそらく25名くらいから）
10名のテーブルが3つあるそうなので、テーブル2つ分予約とかでも大丈夫

コース2000円（税込み）9品
飲み放題120分1500円（税込み）
滞在可能時間180分
料理の人数変更は前日まで、飲み放題は当日変更OK

席を確保して、料理の人数を確定させれば、当日の人数変更は対応可能。
足りなければ追加の料理の注文OK

★焼き鳥屋 PaPaROKU【パパロク】武蔵本店
050-5281-1203
石川県金沢市袋町4-30
営業時間17:30-23:30

焼き鳥屋さん
30名の座敷完備（２F）

２F貸し切りは
料理、ドリンク代合計が87500円から可能
当日15時までの連絡で、人数変更2から3名まで可能

**Comment by PharaohKJ** [comment]
もう具体的にお店のかたと交渉中なのでしょうか、それとも、webかどこかに出ている状態を元に話をされてますか？

私の経験上、金沢っぽいものを出してほしい & 宴会したい〜でつきあっていただけたのは

えびやさん
http://www.hotpepper.jp/strJ000989088/
最大宴会収容人数    35人(2階掘りごたつを貸し切りに)

四分一さん 金沢駅前
http://www.daiba-net.co.jp/shibuichi_enkai.html
http://www.daiba-net.co.jp/access.html#inquiry
宴会コース

などです。予算と内容を伝えたら、交渉できると思います。

**Comment by YMatsubara** [comment]
情報ありがとうございます。
交渉はしていないです、Webを元に探して、お店に電話での問い合わせの段階です。

金沢っぽいもので限定していると、予算4000円から5000円になってしまうので
なかなか見つかっておりません。

上記お店、飲放題付きで、予算交渉してみたいと思います。

**Comment by PharaohKJ** [comment]
期待してます！よろしくお願いします！

**Comment by PharaohKJ** [comment]
口福さんに決定し、connpass側も更新

http://connpass.com/event/30846/

移動方法は歩きでOK
