### ISSUE TITLE
飲食物の準備

### ISSUE THREAD

**Issue by PharaohKJ** [osunc-kanazawa/osunc-kanazawa#4]
- 会場内調理禁止
- ご当地B級グルメ的なのがいいのではないか
- [ ] 飲み物を配る方法
- [ ] 飲み物を冷やす方法

**Comment by PharaohKJ** [comment]
- [ ] ごみ処理、分別方法確認(持ち帰り含めて)
- [ ] 食べ物手配
  - [ ] 買い出し場所の決定
  - [ ] 買い出し担当者の決定
  - [ ] ケータリング業社選定(やるなら)

**Comment by takuya-matsumura** [comment]
食べ物について
川越は普通にスーパーで購入してきたコロッケとかサラダとかと，店先で売られている焼き串とか焼きそばでした．それら，ご当地特有のものとのこと．
全国行脚している人たちも来られますので，地元のもの（夜の懇親会では食べ無さそうな地元のもの）を集められるといいなぁ，と思います．
ですので，ケータリング業者の選定というより，買い出しです．

**Comment by takuya-matsumura** [comment]
飲み物について
川越はビールサーバーと冷蔵庫を持ち込んでました．
冷酒とか，2Lのペットボトル飲料を冷蔵庫に入れてました．
ここまで大掛かりなことはしたくないので，クラーボックス数個で飲み物を冷やすというのでどうでしょうか．
飲み物は，一箇所にまとめて置いてあり各自が好きなものを好きなときに飲んでいましたので，ビールはあっという間に無くなってしまってたようです．
あとは，日本酒・ワイン・梅酒の差し入れが大量にありましたので，それを楽しまれてました．
ビール，缶だとゴミ処理まで考えると面倒ですかね．

**Comment by PharaohKJ** [comment]
> 食べ物について

ああ、なるほど、そういうやりかたですね。いいと思います。というか業社手配というと業社手配しないといけないので、タイトルを変えてしまいます。

> 飲み物について

お酒差し入れコーナーとか置いておいて勝手に飲むスタイルですかね？それがいいかもですね。
とりあえず持ち込み可能とかにしちゃえば、缶は持ち込まないで下さいというのは無理だと思うので
分別・持ち帰りにご協力ください、としてありにしちゃわないといけないかなーと考えます。
- お酒差し入れ・持ち込みコーナーの検討
  - [x] 会場レイアウトのどこにするか決定
  - [x] 運用方法の決定
  - [x] 冷やし方の検討と決定
  - [x] 分別・持ち帰りの案内方法の決定

**Comment by PharaohKJ** [comment]
なんか、いろいろ調べてたら、会費とって、そのなかで運営する、より、もうみんな入場料として、飲み物か、メシか、おやつ、を、持ってきて下さい。っていって、会場におけるそれらの置き場所だけ決めとけばいい気がしてきた。

**Comment by takuya-matsumura** [comment]
県外組にも，持ってきてって言います？
県内参加組は，それでもいいでしょうけど，，，
いや，でも，どれだけの量を持っていけばいいのか，分からないのと違います？

**Comment by PharaohKJ** [comment]
いや、私もそう思います。ただ、なんか全部こちらで用意する、というのはアンカンファレンスとは何か？という資料を用意してて、コンセプトが違うのかなーと思ったりしただけです。

会費とって、それで飲食物かって、やるんだったら、それはただの異業種交流会では・・・。
まぁ一発目だし、まずはそれでええやん？という話ならそれでいいのかなとは思いますが。

アンカンファレンスの説明には、「本来はこうなんだけど、今回はまだ見えないので会費とって、こちらで飲食用意します。飲食物の持ち込みは大歓迎です」という旨にして進めましょうか。

**Comment by tmiyahar** [comment]
県外組にも持ってきて、でいいと思います。
日本酒、焼酎等、持って行くと思いますよ。
量は目安を言っておけばいいと思いますよ（日本酒、焼酎なら4合瓶、ワイン1本などなど）

**Comment by takuya-matsumura** [comment]
では，飲み物の差し入れは大歓迎ということで．
食べ物も，もちろん大歓迎．
とりあえず，ビールとある程度の料理は考えましょうかね．

**Comment by YMatsubara** [comment]
![image](https://cloud.githubusercontent.com/assets/19628579/17795769/092834ec-65f6-11e6-9323-39ed40c31333.png)

内訳はこんな感じで考えています。

**Comment by YMatsubara** [comment]
持ち込みの量が読めないので、仕入れつつ状況が変化しても対応できるよう。直前に仕入れられるものは、なるべく直前に仕入れようと思います。

**Comment by YMatsubara** [comment]
ご報告。

仕入れに関してほぼ完了しました。

飲み物、お酒、お菓子類などはもうすでに手元にあります。お皿、箸、コップ、ゴミ袋、布巾、お持ち帰り用の小袋などもすでに準備はOKです。

また、オードブルや芝ずしなどの軽食は13時に会場に到着するよう手配済みです。受付の方に受け取って、その場で支払いをする形となりますのでよろしくお願いいたします。

**Comment by PharaohKJ** [comment]
無事完了しました。
