### ISSUE TITLE
タイムテーブル、参加費の決定

### ISSUE THREAD

**Issue by PharaohKJ** [osunc-kanazawa/osunc-kanazawa#5]
発表がどんな内容がいいのかわからないので、誰かなんかサンプルを提示して欲しい。
ガチ開発じゃないほうがいいようだ。

あと、予算を確定させたい。ノンアルコール￥500、アルコール￥1000円ぐらいが目標じゃないか？
- [x] タイムテーブルの決定
- [x] 予算の確定

**Comment by takuya-matsumura** [comment]
会費について
アルコールで会費を分けるのはやめませんか？
実際，始まると，誰がどうだったか，誰がなにを飲んでるかまで，管理できませんし．

**Comment by takuya-matsumura** [comment]
発表内容
真面目なものでいいです．
不真面目なものでもいいです．
IT以外でもOK，OSCに拘る必要もない．
ただ，やっぱりIT系のイベントですので，最後の落ちはIT系らしく，かなぁ．
川越の発表スライドが，どっかに落ちてるはず．．．

**Comment by PharaohKJ** [comment]
> 会費について
> アルコールで会費を分けるのはやめませんか？
> 実際，始まると，誰がどうだったか，誰がなにを飲んでるかまで，管理できませんし．

どうやって飲み物を配るかってことになるのかと考えます。私は受付時にお酒を渡すとか、ネームプレートにアルコール有りの色にするとかそういう運用でじゅうぶんかなと考えました。

しかしながら、本来の考えとしては、ノンアルコール = 学生、学割ぐらいのつもりで意見を出しました。値段が統一されるのは望ましいと考えますが、現状、「タダじゃない」ので「できるだけ安くしたい」という気持ちが強いです。

> 発表内容
> 真面目なものでいいです．
> 不真面目なものでもいいです．
> IT以外でもOK，OSCに拘る必要もない．

なんでもいい、となると、応募するほうもツライので、とりあえず、地元から代表セッションするタイトルとか2本ほど（真面目なの、不真面目なの）出したほうがいいだろうなあと考えます。どうでしょう？

**Comment by takuya-matsumura** [comment]
会場費は，びぎねっとさんが負担されていますよね．
会費でカバーするのは，会場での飲食のみですかね？

**Comment by PharaohKJ** [comment]
そうですね。ちょっと @tmiyahar さんに確認とる必要がありますね。

すみません @tmiyahar さん、会場費はいったん私が建て替え、びぎねっとさんに請求するということにしてあります。当日、会費を集めますが、「会場費はそのなかから払って欲しい」のか「びぎねっとさんが出していただける」のか、ご回答願えますでしょうか？

びぎねっとさまが負担していただけるのならば、「飲食」「設営用文具購入など」で集めたい (& 金額は安くできるかな？) と思います。

**Comment by takuya-matsumura** [comment]
会費をどういう風に扱うのか，という点も決めていただかないといけないですよね．
もしかしたら県外組の交通費補助も必要かもしれませんしね．今まで他地域でどのように費用を支出してきたのかを我々は知りません．
OSunCという名前のイベントですから，宮原さんの考えをまずはお聞きしましょう．

**Comment by tmiyahar** [comment]
お金については、ある程度自由に決めていただいても構いませんが、これまでのOSC、OSunC的には大体以下の通りです。

会費：2000円ぐらい（お店を使う場合にはお店の代金をベースに考える）

会場費：今回はびぎねっとで持つことにしていますが、会費から捻出してもいいし、協賛企業を募ってもよいかも？

その他の経費：必要となりそうなものはすべてびぎねっとで持っているので、文房具等の購入はよほ
どのことが無い限り不要かと思います。

見学組の交通費補助：基本的に不要です。来たい奴は自力で来い、が原則です。

学割：学生1名はおっさん3人分ぐらいの価値があるので、会費割引き等優遇してあげてください。会費2000円なら、学割で1000円（高校生なら無料）ぐらいの感じでしょうか。

**Comment by PharaohKJ** [comment]
ありがとうございました。それではいったんこの価格
- 一般 2,000円
- 学生 1,000円
- 高校生以下 無料

で進めたいと思います。どうでしょうか？特に反対なければこれでいきましょう。

**Comment by takuya-matsumura** [comment]
金額，異論なし．
これで予算は立ちやすくなったかな？

**Comment by nkmc-ja** [comment]
OKです。サイト更新しておきました。
詳しくは #12 でご確認ください。

**Comment by PharaohKJ** [comment]
みんなでLTというわけで決定。予算もまぁ確定だろうので close いたします。
