### ISSUE TITLE
会場設営

### ISSUE THREAD

**Issue by PharaohKJ** [osunc-kanazawa/osunc-kanazawa#6]
当日の午前に机など配置する。
手分けする担当者を集める、決めるしてください。

**Comment by PharaohKJ** [comment]
- [ ] 会場レイアウトの設置担当者決定
- [ ] 同撤収担当者決定

**Comment by takuya-matsumura** [comment]
必要品にネームプレートを書いておきましたが，2種類必要なことを書き忘れました．
写真撮影NGな人がいらっしゃるようです．
一目で分かるようなもの（色分けするとか）が望ましいです．

**Comment by PharaohKJ** [comment]
わかりました。ちょっとタスク分けてしまいます。

受付については #10 でやりましょう。

**Comment by PharaohKJ** [comment]
無事完了しました。
