### ISSUE TITLE
司会進行

### ISSUE THREAD

**Issue by PharaohKJ** [osunc-kanazawa/osunc-kanazawa#7]
担当者を決めてクローズ

**Comment by PharaohKJ** [comment]
- [x] 総合司会担当決め
  - 担当は @seiken-tk 
- [ ] LTタイムキーパー(ドラ担当含む)決め

**Comment by takuya-matsumura** [comment]
司会　自分がやりましょうか．．．
ふざけた司会は出来ませんので，粛々と．．．

**Comment by PharaohKJ** [comment]
おっとすみません、総合司会は @seiken-tk さんがいったん名乗りでてる状況です。

**Comment by takuya-matsumura** [comment]
そうなんですね．担当が決まっているところは，担当を書いといて頂けます？

**Comment by PharaohKJ** [comment]
書いておきました。ほか、司会のヘルプ、LTタイムキーパーなど、必要でしたら @seiken-tk さんここで続けて下さい。特に必要なければクローズしてください。

**Comment by seiken-tk** [comment]
ありがとうございます。
では、どなたかLTのタイムキーパー兼司会のヘルプやっていただけますか？
LTの経過時間をストップウォッチではかる、3分前、1分前と書かれた紙を発表者に見えるように掲げるぐらいでOKだと思います。
司会のヘルプはいまのところとくに必要ないと思いますが、一応タイムキーパーと兼任ということでお願いします。

**Comment by tmiyahar** [comment]
タイマーはiPad用のタイマーアプリを使っています。カウントダウン式で、1分前に黄色、30秒前に赤になるので、喋っている人に見えるようにしておけば大丈夫です。
ドラも持って行きます。

**Comment by seiken-tk** [comment]
了解です。ありがとうございます。

**Comment by PharaohKJ** [comment]
無事完了しました。結局誰もドラやタイマー使いませんでしたね！まぁ時間がオシてたわけじゃないからいいかあ。
