### ISSUE TITLE
展示者窓口

### ISSUE THREAD

**Issue by PharaohKJ** [osunc-kanazawa/osunc-kanazawa#8]
準備会への連絡はここをお使いください。

詳細は 募集ページ及び wiki

http://connpass.com/event/30813/
http://connpass.com/event/30846/

にまとめていく予定です。

**Comment by PharaohKJ** [comment]
GitHubアカウントが無い方は、 kato+osuc@phalanxware.com までメールください。

**Comment by nkmc-souya** [comment]
展示希望者より、荷物の配送についての問い合わせがありました。

> 展示と発表で申し込んでおりますが、展示道具をスーツケースに詰め込んで、事前に宅配で送りたいと考えております。
> 
> 参加申込時にもお尋ねしたのですが、宅配荷物を受け取りしていただけますでしょうか。
> もし受け取りしてもらえる場合の送付先住所等もご指示いただけますと助かります。
> よろしくお願い致します。
> ※一部個人情報のため削除

確認になりますが、ITプラザ武蔵からは

> 前日必着でダンボール３個までなら、お預かりできます。それ以上ですと、前日夜間のお部屋を追加ご予約いただき、お部屋に直接入庫となります。

と回答いただいてますが、スーツケースのサイズでも大丈夫でしょうか。
（サイズによりけりと思いますので、希望者に確認いたします。）

**Comment by PharaohKJ** [comment]
明日(8/9)に武蔵さんと交渉し、ダメだったら私の家か、ちょっと他あたってみます。

**Comment by nkmc-souya** [comment]
よろしくお願いします。

**Comment by PharaohKJ** [comment]
ITプラザ武蔵と話しましたが、やはり大量になると部屋をかりてそこに置いて、翌朝即自室に持ち込んで欲しいとのこと。

一番狭い会議室で5000円/日

当日の集荷についてはクロネコヤマトと交渉中です。

確定したら相談させてください。

**Comment by nkmc-souya** [comment]
ご確認ありがとうございます。
スーツケースについは具体的なサイズは確認していただいておりますが、
機内持ち込み可～一回り大きいぐらいのスーツケースが１つとなりそうです。

※他の展示者の方にもご連絡いれたほうがいいですね。確定したらアナウンスいたします。

**Comment by PharaohKJ** [comment]
クロネコさんとの交渉は、当日夜集荷にお伺いできます。ってことになりました。

なので、前日の会議費の支出について相談します。

**Comment by PharaohKJ** [comment]
@tmiyahar さんと相談しました。基本、持ち込みですが、どうしてもという方は、いったん、準備会に連絡いただき、 @PharaohKJ まで送ってもらい、当日、私が搬入し、当日、送り返してもらうという形にします。

なので、「会場まで荷物を送る・会場から荷物を送る予定の方は問い合わせください」とし、あった方は
- お名前(団体名)
- 量

をお伺いしてください。
- 前日必着
- @PharaohKJ の住所

を案内してください。

その結果、すごい量の申し込みがない限りは、私が対応します。あった場合にはまたご相談させてください。

**Comment by nkmc-souya** [comment]
調整ありがとうございます。

先の展示品宅配希望の方ですが、地元の方と調整されて、会場からの発送のみ必要となりました。

現在、お荷物の状況としては以下になります。
・会場への送付希望者： 0
・会場からの送付希望者： 1

**Comment by PharaohKJ** [comment]
わかりました。ありがとうございます。

2016年8月11日(木) 16:32 nkmc-souya notifications@github.com:

**Comment by PharaohKJ** [comment]
各位 とレイアウト担当 @Yuk11 さん
https://www.dropbox.com/s/gwv2oe2c2nt2hnp/レイアウト.png?dl=0
ITビジネスプラザ武蔵さまがパネル展示を行いたいとのことで、このコメントしたところでよろしいでしょうか？
あと @nkmc-souya さん、展示者さんそれぞれの席決めのために、このレイアウト図に名前を入れていきたいのですが、名簿をいただけますか？(もしくは、 @Yuk11 さんと相談して配置お願いします、当日でいいとも思います)

武蔵さんへの返事はなるべくはやくしたいので、そこだけお願いします。

**Comment by yukimuraaa** [comment]
レイアウト図への展示者さんの名前入れはこちらで担当します．

武蔵さんの展示位置は問題ないと思います．

**Comment by tmiyahar** [comment]
アンカンファレンスなので、ブースの位置決めは当日その場で決めましょう。
レイアウト自体、現場でエイヤ！ぐらいでいいと思います。

もちろん、発表順も当日決めましょう。

**Comment by PharaohKJ** [comment]
@tmiyahar さん @Yuk11 さん、わかりました。ありがとうございます。
とりあえず展示OKと伝え、当日きてくださいと伝えておきます。

**Comment by tmiyahar** [comment]
あ、もちろん、配置図のブース数を見て、全然余裕じゃん、という前提があるから言い切ってますよ。

といっても、キツキツの場合でも、その場で決める感じですけどね。

極力、事前の準備をやらないでも大丈夫！イベントやれるじゃん！という実験なので、皆さん、徹底的に手を抜いて、サボって、失敗しましょう。

**Comment by tmiyahar** [comment]
あ、レイアウトについて少しだけ。

まず、外側の壁を背に配置するのが良いと思います。ですので、配置案の右側が未使用ですが、そっちを先に使った方がいいと思います。

次に、それで足りなかった場合、真ん中の島を作る事になりますが、もし、背中合わせにする必要が無いなら、前方スクリーン向きに配置しましょう。もし、今のように背中合わせの島を作る場合、右側の列の人がスクリーンに背を向けることになるので、むしろスクリーンに向けて直角（図面横方向）に並べる方が良いでしょうか。

あと、飲食物のテーブルがどーんと大きすぎるので、小分けにデキルといいかなと思います。
いずれにしろ、当日朝にエイヤ！ですね。

**Comment by PharaohKJ** [comment]
無事完了しました。
