### ISSUE TITLE
広報活動

### ISSUE THREAD

**Issue by PharaohKJ** [osunc-kanazawa/osunc-kanazawa#9]
- [ ] 定期的に募集をシェアする
- [x] 広告用ペラ一枚を作る。稿のチェックはFBで。終わったらPDFで共有。

ほか、ペラ印刷して配った。どこどこに広報にいった、などあれば、ここで報告してください。

**Comment by takuya-matsumura** [comment]
広告用ベラの作成は加藤さん？

**Comment by PharaohKJ** [comment]
はい。ペラは @PharaohKJ が、とりあえず来月半ば目標で作ります。月曜(5/30)に、デザインできる方と打ち合わせする予定です。いったん 6/18 目標で進めます。

募集のSNSシェアについても、定期的にFBなどで、「各位はSNSに拡散お願いします」と書きますので、各位ご協力お願いします。

**Comment by seiken-tk** [comment]
SNSシェアの件、了解です。
- [ ] 県内IT系学部のある大学・専門学校・高専への告知
- [ ] 県内IT企業への告知
- [ ] これまでのOSCに出展されているような企業・個人の方への告知

出展のお願い、企業ノベルティグッズ（会社ロゴシールなど）・チラシ提供のお願い、社員・学生へのイベント告知のお願い等を企業や大学に対して行っていきたいなと考えております。

**Comment by PharaohKJ** [comment]
ありがとうございます。働きかけを行ったらできればここでご報告お願いします。
とりあえず @PharaohKJ 分の計画書いておきます。
- [x] 共用キーノートを作成する
- [x] Kanazawa.rb 46 (6月
- [ ] Kanazawa.rb 47 (7月
- [ ] Kanazawa.rb 48 (8月
- [x] JAWS-UG 金沢 (6月
- [x] JAWS-UG 金沢 (7月
- [x] C8LINKさまにお声がけ

**Comment by PharaohKJ** [comment]
昨日(5/30)、 C8LINKさまにお声がけしておきました。展示もしていただけそうです。

**Comment by PharaohKJ** [comment]
- [ ] ITプラザ武蔵にペラの設置

**Comment by PharaohKJ** [comment]
ペラですが、ちょっと書くことが日付以外未定すぎて、難しいということになってしまいました。いったん、もちこみ、展示会費、など決まってきたら、作成するかも、という方向でお願いします。

**Comment by PharaohKJ** [comment]
https://codeforkanazawa.doorkeeper.jp/events/46358
https://www.facebook.com/CivicHackNight

でiCloudのスライドを元にプレゼンしてきました。

20人ぐらいいらっしゃってまして、会場(ITプラザ武蔵)がぜひ協力して進めたいとの言質いただきました。

**Comment by PharaohKJ** [comment]
JAWS-UG 金沢 6月 で集客してきました。

**Comment by takuya-matsumura** [comment]
来週の月曜(6/20)　金沢大学　浅川教授（理工学域　機械工学系）に協力のお願いをしてきます．
学内告知・集客・スタッフ（学生さん）の観点での協力依頼となります．
（弊社 八木が先生の授業を受けていたようなので，一緒に行きます．）

**Comment by PharaohKJ** [comment]
本日、ペラ1枚お願いする方に仕様伝えてきました。来週末には案出せそうです。

**Comment by seiken-tk** [comment]
- [x] 株式会社グランゼーラ
- [x] 株式会社双子ゲームス
- [ ] 株式会社リュウテック
- [ ] サイバーステーション株式会社
- [x] ファースト学園金沢校
- [ ] 北陸先端科学技術大学院大学

本日、グランゼーラさんにお話してきました。社員さんたちに告知してくれるとのことでした。感触は良かったです。
ちょいちょい県内のIT系企業さんにお話していこうと思うので、でき次第チェック入れていきます。

**Comment by PharaohKJ** [comment]
ありがとうございます。コンテンツ勢ですね。それでは私はエーアイさんにこえかけておきます。
金沢工業大学も何人かの先生にこえかけておきますね。
- [x] [株式会社AI](http://www.anima-i.co.jp)
- [x] 金沢工業大学

**Comment by takuya-matsumura** [comment]
弊社が対法人に対して告知したもの（僅かですが）に関して，企業名は伏せさせてもらいますのであしからず．
石川高専 電子情報は，インターンシップの関係で連絡しないといけないので，ペラが出来次第連絡する予定です．

**Comment by PharaohKJ** [comment]
JAWS-UG 金沢 7月 on C8LINK さんで集客してきました。

木曜日に ITビジネスプラザ武蔵 行くついでにペラカラー印刷して持ち込もうかなと考えています。
Civic Hack Night において、宣伝します。

その印刷に問題なさそうなら激安の印刷所適当に探してまわそうかなー？と考えています。
各自、印刷だとすごいお金かかってしまいそうですけどそのほうが必要最低量だけ作るからいいですかねえ？

**Comment by takuya-matsumura** [comment]
開催まで一月半になってしまってますから，わざわざ印刷屋に出すほど枚数が必要になるか疑問です．
あと，ひと月・ふた月ほど早ければ．．．と思います．
どうしてもペーパーじゃないと，というところ以外は，メール等で良いのではないでしょうか．
ペーパーもモノクロで，良さそうなところは，モノクロでもいいと思いますが．

**Comment by PharaohKJ** [comment]
ありがとうございます。それではそれで。

印刷などする必要があって、してどこかに持っていく場合にはここで一報いただければと思います。

**Comment by PharaohKJ** [comment]
Civic Hack Night で宣伝いたしました。

その会場で、とある方から、 n-project のお酒を差し入れいただきました！
https://www.makuake.com/project/n-project/

諸事情により、名前は伏せて欲しいとのことですが、確かに @pharaohkj がお預かりいたしました。

**Comment by PharaohKJ** [comment]
無事完了しました。
